### ISSUE TITLE
bigger rootfs size

### ISSUE THREAD

**Issue by nextgen-networks** [efahl/owut#15]
My system:
Banana Pi BPI-R4 on OpenWRT Snapshot builds

I've a 64 GB SDCard as system device.
Partition 7 (overlay) is expanded to maximum remaining space after initial install (58 GB - with cfdisk)

I found your script very useful as I do often upgrades to latest builds via https://firmware-selector.openwrt.org/ 

Was a bit puzzled if the partition size will be kept and therefore added the rootfs size to the upgrade/install script:
`owut install --rootfs-size 57000`
This throws an error
`ERROR: 57000 above upper bound 1024`

Is it possible to increase the maximum root partition size?

Thanks for your great work on owut!

**Comment by efahl** [comment]
Thanks, I was wondering how long it would take for someone to ask this.  Apparently not very long!  I'm going to write an FAQ, and your question will be "First!"  Anyhow, the answer to your question is...

The upper bound is dictated by the ASU server for practical reasons.  The way the partitions are created on some devices requires that the full-sized image be created and then compressed, which takes both a _lot_ of RAM, disk and time.  

As a test, I just did a couple of imagebuilder runs with rootfs partitions of 10000 and 20000 to see how long they would take (I copied my previous results from the PR when the limit was raised to 1024, https://github.com/openwrt/asu/pull/827):

| ROOTFS_PARTSIZE= | real | user | img size |
| ---------------: | ----: | ----: | --------: |
|  104 |  26s |  18s |  12M |
|  512 |  48s |  25s |  13M |
| 1024 |  74s | 33s |  13M |
| 10000 |  11m47s | 4m36s | 32M |
| 20000 | 28m15s | 13m9s | 32M |

Those last two rows should make fairly clear why increasing the upper limit is infeasible, until such time as the build process is reworked to reduce the time required to create larger images.

Note: the above tests were all run on an AMD R9 7950x 5.8GHz CPU with 64GB CL6000 RAM and PCIe 4 SSD, which is generally 3x faster than the ASU server hardware, so these numbers are _well_ below what you'd see if using ASU server.
