### ISSUE TITLE
warn (and maybe abort?) in case of downgrades

### ISSUE THREAD

**Issue by dangowrt** [efahl/owut#17]
`owut` happily downgrade packages which have newer versions in the currently running image.

```
Package version changes:
  libucode                   2024.07.11~1a8a0bcf-r1                     2024.06.18~4dd98370-r1
  ucode                      2024.07.11~1a8a0bcf-r1                     2024.06.18~4dd98370-r1
  ucode-mod-fs               2024.07.11~1a8a0bcf-r1                     2024.06.18~4dd98370-r1
  ucode-mod-nl80211          2024.07.11~1a8a0bcf-r1                     2024.06.18~4dd98370-r1
  ucode-mod-rtnl             2024.07.11~1a8a0bcf-r1                     2024.06.18~4dd98370-r1
  ucode-mod-ubus             2024.07.11~1a8a0bcf-r1                     2024.06.18~4dd98370-r1
  ucode-mod-uci              2024.07.11~1a8a0bcf-r1                     2024.06.18~4dd98370-r1
  ucode-mod-uloop            2024.07.11~1a8a0bcf-r1                     2024.06.18~4dd98370-r1
```
Those lines should be in red or otherwise highlighted, and `owut` should not proceed unless the *force* option is given.

**Comment by efahl** [comment]
Thanks, that's a nice addition.

Did a major rework of package version parsing, what a mess.  Is there some code somewhere that we could put in a ucode-mod so everyone could use it?  Seems like with the APK work, something like that should exist...

Anyhow, all done in https://github.com/efahl/owut/commit/0aefe77e47d4b88fc4ae7ee516a380e64b64d6c1
